#motor 1,2 should be on left, 3,4 should be right
#1,3 should be front
#python3 -m pip install gpiozero
from gpiozero import Motor
import time
motor1 = Motor(4, 14)
motor2 = Motor(17, 27)
motor3 = Motor(23, 24)
motor4 = Motor(2, 3)
motor1.forward()
motor2.forward()
motor3.forward()
motor4.forward()
time.sleep(3)
print("backwards")
motor1.reverse()
motor2.reverse()
motor3.reverse()
motor4.reverse()
time.sleep(3)
print("testing 0.5 speed left 2 will move at half speed")
motor1.forward()
motor2.forward()
motor3.forward(0.5)
motor4.forward(0.5)
time.sleep(3)
print("strafe left")
motor1.forward()
motor2.backward()
motor3.backward()
motor4.forward()
time.sleep(3)
print("strafing right")
motor1.backward()
motor2.forward()
motor3.forward()
motor4.backward()